apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cronjobs-s3manager
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
#    nginx.ingress.kubernetes.io/auth-type: basic
#    nginx.ingress.kubernetes.io/auth-secret: {{ .Release.Namespace }}-basic-auth
#    nginx.ingress.kubernetes.io/auth-realm: "Kibana Authentication Required - kibanaadmin"
spec:
#  {{- if .Values.ingress.tls }}
#  tls: {{- toYaml .Values.ingress.tls | nindent 2 }}
#  {{- end }}
#    secretName: {{ .Values.ingress.secretName }}
  rules:
#  - host: {{ .Values.ingress.host.kibana }}
  - host: s3manager.agat.local
    http:
      paths:
      - path: /
        backend:
          serviceName: s3-manager-service
          servicePort: 8888
