apiVersion: v1
kind: Service
metadata:
  name: s3-manager-service
spec:
  selector:
    app: s3manager
  ports:
  - protocol: "TCP"
    port: 8888
    targetPort: 8888
#    nodePort: 8888
  type: NodePort